desc 'Generates a secret token for the application.'
task :generate_secret_token do
  path = File.join(Rails.root, 'config', 'initializers', 'secret_token.rb')
  secret = SecureRandom.hex(40)
  File.open(path, 'w') do |f|
    f.write <<"EOF"
# This file was generated by 'rake generate_secret_token', and should
# not be made visible to the public.
Photolesce::Application.config.secret_token = '#{secret}'
EOF
  end
end
